### PR TITLE
Sec 1 Registration announcement

### PR DESCRIPTION
**Pull request by ISOMERGITHUB33**
Took out the N Level announcement banner and replaced content with Sec 1 Registration announcement.

### CODE REVIEW

**Review by Shasikumaran — COMMENTED** [review]
Thank you Siti

**Review by Shasikumaran — COMMENTED** [review]
Thank you

**Comment by Shasikumaran** [comment]
Thank you Siti

**Review by Shasikumaran — COMMENTED** [review]
approved

**Review by isomeradmin — APPROVED** [review]

**Pull request merged**
